---
- include_vars: vault.yml

- name: install packages required for backup
  apt: pkg={{ item }} state=present
  with_items:
    - rsync
    - rsnapshot

- name: install snapraid configuration
  copy:
    src: etc/{{ snapraidconf|basename }}
    dest: "{{ snapraidconf }}"
    owner: root
    group: root
    mode: 0775

- name: clone snapraid-runner
  git:
    repo: https://github.com/Chronial/snapraid-runner.git
    dest: /opt/snapraid-runner

- name: setup cron for rsnapshot and snapraid
  cron:
    user: "root"
    job: "{{ item.job }}"
    name: "snapshot-{{ item.name }}"
    weekday: "{{ item.weekday }}"
    minute: "00"
    hour: "{{ item.hour }}"
    dom: "{{ item.dom|default('*') }}"
  with_items:
    - { job: '{{ snap_run_command }}', name: 'snapraid_runner', weekday: '*', hour: '08' }
  tags:
    - cron
