################################################################################
# nfs
################################################################################
- name: install nfs
  apt:
    pkg: nfs-kernel-server
    state: present
  notify:
    - start nfs service

- name: install nfs config
  copy:
    src: etc/exports
    dest: /etc/exports
    owner: root
    group: root
  notify:
    - exportfs
    - restart nfs service