---
# epsilon specific setup
- name: configure base-os
  include: base-os.yml
  when: base-os
  tags: baseos

- name: configure mounts
  include: mounts.yml
  when: mounts
  tags: mounts

- name: configure backups
  include: backups.yml
  when: backups
  tags: backups