galaxy_info:
  author: Jesper Rasmussen
  description: |
    Ansible Galaxy role to manage common storage for downloaders for mediaserver
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
       - trusty
  galaxy_tags:
    - docker
    - ubuntu
dependencies: []
